package fr.bubblebd

/** French source labels are stable internal keys. Add translations here, not in stored data. */
internal object UiCatalog {
    val entries: Map<String, String> = linkedMapOf(
        "Droite vers gauche" to "Right to left",
        "Gauche vers droite" to "Left to right",
        "Page hors limites" to "Page out of range",
        "Image non prise en charge" to "Unsupported image format",
        "Aucune page image dans cette archive" to "No image pages in this archive",
        "Aucune page image" to "No image pages",
        "Source inaccessible" to "Source unavailable",
        "ZIP sans répertoire" to "ZIP directory missing",
        "Lecture partielle indisponible" to "Partial download unavailable",
        "Trop de redirections OneDrive" to "Too many OneDrive redirects",
        "BDThèque est temporairement indisponible." to "BDThèque is temporarily unavailable.",
        "Adresse BDThèque invalide" to "Invalid BDThèque address",
        "Les informations de cette fiche ne sont pas récupérables automatiquement." to "Information on this page cannot be retrieved automatically.",

        "Vos albums" to "Your books",
        "Les informations des BD" to "Book information",
        "Accueil" to "Home",
        "Bibliothèque" to "Library",
        "Réglages" to "Settings",
        "Icône BubbleBD" to "BubbleBD icon",
        "Revenir à la lecture de gauche à droite" to "Switch to left-to-right reading",
        "Activer la lecture manga de droite à gauche" to "Switch to right-to-left manga reading",
        "Passer au thème jour" to "Switch to light theme",
        "Passer au thème nuit" to "Switch to dark theme",
        "Reprendre la lecture ?" to "Resume reading?",
        "Reprendre" to "Resume",
        "Première page" to "First page",
        "Recherche des infos" to "Looking up book information",
        "Vos BD, simplement." to "Your comics, made simple.",
        "Ajoutez vos dossiers pour retrouver vos albums et reprendre votre lecture en un geste." to "Add your folders to find your comics and pick up where you left off.",
        "Ajouter mes BD" to "Add my comics",
        "À reprendre" to "Continue reading",
        "Derniers ajouts" to "Recently added",
        "Voir tous les albums" to "View all books",
        "Disponible en local" to "Available offline",
        "Album cloud" to "Cloud book",
        "Album à vérifier" to "Book needs attention",
        "Affichage couvertures" to "Cover view",
        "Affichage grille" to "Grid view",
        "Affichage liste" to "List view",
        "Tous" to "All",
        "En cours" to "In progress",
        "Non lus" to "Unread",
        "Terminés" to "Finished",
        "À lire" to "To read",
        "Lu" to "Read",
        "Non lu" to "Unread",
        "Terminé" to "Finished",
        "Partout" to "Everywhere",
        "Local" to "Local",
        "Cloud" to "Cloud",
        "Titre, série, auteur…" to "Title, series, author…",
        "Trier et régler la taille" to "Sort and change cover size",
        "État de lecture" to "Reading status",
        "Emplacement" to "Location",
        "Votre bibliothèque est vide." to "Your library is empty.",
        "Aucun album ne correspond à cette recherche." to "No books match your search.",
        "Choisir mes dossiers" to "Choose my folders",
        "Affichage et tri" to "View and sorting",
        "Couvertures par ligne" to "Covers per row",
        "Croissant" to "Ascending",
        "Décroissant" to "Descending",
        "Les plus anciennes lectures en premier" to "Least recently opened first",
        "Le dernier album ouvert en premier" to "Most recently opened first",
        "Dernière ouverture" to "Last opened",
        "Titre" to "Title",
        "Série" to "Series",
        "N°" to "No.",
        "Parution" to "Publication date",
        "Genre" to "Genre",
        "Dessinateur" to "Artist",
        "Scénariste" to "Writer",
        "Éditeur" to "Publisher",
        "Ajout" to "Date added",
        "Progression" to "Progress",
        "Informations des BD" to "Book information",
        "Relancer la recherche des infos" to "Look up book information again",
        "Mes dossiers" to "My folders",
        "Aucun dossier ajouté" to "No folders added",
        "Dossier Android" to "Android folder",
        "Retirer ce dossier du scan" to "Stop scanning this folder",
        "Ajouter un dossier" to "Add a folder",
        "Scanner" to "Scan",
        "Albums supprimés" to "Removed books",
        "Stockage local" to "Local storage",
        "Limite en Mo" to "Limit in MB",
        "Cache vidé. Les copies conservées hors ligne sont intactes." to "Cache cleared. Offline copies have been kept.",
        "Vider le cache" to "Clear cache",
        "Lecture guidée" to "Guided reading",
        "Assombrissement hors case" to "Dim outside the panel",
        "À propos" to "About",
        "Retirer ce dossier ?" to "Remove this folder?",
        "Il ne sera plus scanné. Les fichiers, les albums déjà indexés et leur progression sont conservés." to "This folder will no longer be scanned. Files, indexed books and reading progress will be kept.",
        "Retirer" to "Remove",
        "Annuler" to "Cancel",
        "Choisir un dossier OneDrive" to "Choose a OneDrive folder",
        "Connecter OneDrive" to "Connect OneDrive",
        "Déconnecter OneDrive" to "Disconnect OneDrive",
        "Déconnecter OneDrive ?" to "Disconnect OneDrive?",
        "Les dossiers OneDrive ne seront plus accessibles. Les copies hors ligne restent disponibles." to "OneDrive folders will no longer be accessible. Offline copies will remain available.",
        "Déconnecter" to "Disconnect",
        "Album fictif de démonstration · pages répétées" to "Fictional demo book · repeated pages",
        "Note non disponible" to "Rating unavailable",
        "Marquer Lu" to "Mark as read",
        "Supprimer" to "Remove",
        "Modifier la fiche" to "Edit book details",
        "Libérer la copie hors ligne" to "Remove offline copy",
        "Télécharger" to "Download",
        "Supprimer cet album ?" to "Remove this book?",
        "Il sera retiré de BubbleBD avec ses copies de lecture. Ses infos, sa progression et sa première page restent enregistrées. Le fichier original est conservé. Les prochains scans ne le réimporteront pas automatiquement." to "The book and its reading copies will be removed from BubbleBD. Its details, progress and first page will be kept. The original file will not be deleted. Future scans will not import it again automatically.",
        "Figer les informations" to "Lock book details",
        "Exclure cette fiche des recherches." to "Exclude this book from information lookups.",
        "Rechercher pour ce titre" to "Look up this book",
        "Résumé" to "Summary",
        "Enregistrer" to "Save",
        "Fermer les albums supprimés" to "Close removed books",
        "Tout réimporter" to "Restore all",
        "Aucun album supprimé" to "No removed books",
        "Réimport" to "Restore",
        "Réimporter la sélection" to "Restore selected",
        "Première page inaccessible" to "First page unavailable",
        "Dossier OneDrive" to "OneDrive folder",
        "Dossier parent" to "Parent folder",
        "Réessayer" to "Retry",
        "Aucun sous-dossier. Vous pouvez choisir ce dossier." to "No subfolders. You can select this folder.",
        "Choisir ce dossier" to "Select this folder",
        "Album inaccessible" to "Book unavailable",
        "Impossible d’afficher la page" to "Unable to display the page",
        "Revenir à la bibliothèque" to "Back to library",
        "Fermer le lecteur" to "Close reader",
        "Voir toute la page" to "Show full page",
        "Page précédente" to "Previous page",
        "Page suivante" to "Next page",
        "Numéro de page : glissez pour parcourir, touchez pour saisir" to "Page number: drag to browse, tap to enter a number",
        "Aller à la page" to "Go to page",
        "Aller" to "Go",
        "Page de bande dessinée. Touchez pour afficher les commandes." to "Comic page. Tap to show controls.",
        "Retour aux réglages" to "Back to settings",
        "Lire à votre rythme" to "Read at your own pace",
        "Votre bibliothèque" to "Your library",
        "Données et crédits" to "Data and credits",
        "Code source, licences et crédits" to "Source code, licences and credits",
        "Recherche interrompue. Relancez la recherche depuis les réglages." to "Lookup stopped. Try again from Settings.",
        "Complément éditeur temporairement indisponible." to "Publisher information is temporarily unavailable.",
        "Complément éditeur indisponible." to "Publisher information is unavailable.",
        "Wikipédia temporairement indisponible." to "Wikipedia is temporarily unavailable.",
        "Aucune correspondance suffisamment sûre avec le nom du fichier et la première page." to "No reliable match was found using the filename and first page.",
        "OneDrive déconnecté. Les copies hors ligne restent disponibles." to "OneDrive disconnected. Offline copies remain available.",
        "Dossier retiré du scan. Les albums et leur progression sont conservés." to "Folder removed from scanning. Books and progress have been kept.",
        "Dossier inaccessible" to "Folder unavailable",
        "Import terminé" to "Import complete",
        "Album supprimé de BubbleBD. Fichier original conservé." to "Book removed from BubbleBD. Original file kept.",
        "Suppression de la copie hors ligne…" to "Removing offline copy…",
        "Conservation hors ligne…" to "Saving an offline copy…",
        "Relecture de l’album…" to "Reopening the book…",
        "Image illisible" to "Unable to read the image",
        "Fichier inaccessible" to "File unavailable",
        "Album supérieur à 2 Go" to "Book larger than 2 GB",
        "Autorisation perdue : sélectionnez à nouveau le dossier" to "Permission lost: select the folder again",
        "Limite de 10 000 albums par dossier atteinte" to "The limit of 10,000 books per folder has been reached",
        "Lecture impossible" to "Unable to read this file",
        "Première page illisible" to "Unable to read the first page",
        "Couverture indisponible. Relancez Scanner pour réessayer." to "Cover unavailable. Run Scan again to retry.",
        "Impossible de conserver le fichier temporaire" to "Unable to save the temporary file",
        "La connexion OneDrive attend l’enregistrement de BubbleBD chez Microsoft. Aucun accès à votre compte n’a encore été demandé." to "OneDrive connection requires BubbleBD to be registered with Microsoft. Access to your account has not been requested.",
        "Connexion OneDrive annulée ou refusée." to "OneDrive connection cancelled or denied.",
        "Microsoft n’a pas pu terminer la connexion." to "Microsoft could not complete sign-in.",
        "Reconnectez OneDrive dans Réglages pour ouvrir cet album." to "Reconnect OneDrive in Settings to open this book.",
        "Votre connexion OneDrive a expiré. Reconnectez-vous dans Réglages." to "Your OneDrive session has expired. Sign in again in Settings.",
        "Reconnectez OneDrive dans Réglages." to "Reconnect OneDrive in Settings.",
        "Microsoft refuse l’accès à ce dossier." to "Microsoft denied access to this folder.",
        "OneDrive est temporairement occupé. Réessayez plus tard." to "OneDrive is temporarily busy. Try again later.",
        "Téléchargement OneDrive inaccessible" to "OneDrive download unavailable",
        "Impossible de télécharger cet album OneDrive. Réessayez ou reconnectez-vous." to "Unable to download this OneDrive book. Try again or reconnect.",
        "Quota gratuit atteint" to "Free quota reached",
        "Recherche différée" to "Lookup delayed",
        "Réponse bibliographique trop grande" to "Book information response is too large",
        "Réponse bibliographique non vérifiable" to "Book information response could not be verified",
        "Correspondance non vérifiable" to "Match could not be verified",
        "Recherche en attente" to "Lookup pending",
        "Recherche en cours…" to "Looking up information…",
        "Recherche interrompue · nouvel essai prévu" to "Lookup interrupted · retry planned",
        "Quota gratuit atteint · recherche différée" to "Free quota reached · lookup delayed",
        "Recherche effectuée · informations trouvées" to "Lookup complete · information found",
        "Recherche effectuée · aucun résultat fiable" to "Lookup complete · no reliable match",
        "Recherche déjà effectuée" to "Previously looked up",
        "Google Books indisponible" to "Google Books unavailable",
        "Open Library indisponible" to "Open Library unavailable",
        "Diminuer {0}" to "Decrease {0}",
        "Augmenter {0}" to "Increase {0}",
        "Page {0} sur {1}" to "Page {0} of {1}",
        "Couverture de {0}" to "Cover of {0}",
        "Fiche de {0}" to "Details for {0}",
        "Tome {0}" to "Volume {0}",
        "{0} % lu" to "{0}% read",
        "1 album" to "1 book",
        "{0} albums" to "{0} books",
        "{0} album(s)" to "Books: {0}",
        "Replier {0}" to "Collapse {0}",
        "Déployer {0}" to "Expand {0}",
        "Série · {0} tomes" to "Series · {0} volumes",
        "Scanné le {0}" to "Scanned on {0}",
        "Albums supprimés ({0})" to "Removed books ({0})",
        "Cache temporaire : {0} Mo" to "Temporary cache: {0} MB",
        "Assombrissement hors case : {0} %" to "Dim outside the panel: {0}%",
        "{0} albums · marquage de la série entière" to "{0} books · mark the entire series",
        "{0} sélectionnés" to "{0} selected",
        "{0} sélectionné" to "{0} selected",
        "Sélectionner {0}" to "Select {0}",
        "Première page de {0}" to "First page of {0}",
        "De 1 à {0}" to "From 1 to {0}",
        "Case {0}/{1}" to "Panel {0}/{1}",
        "Cases {0} et {1}/{2}" to "Panels {0} and {1}/{2}",
        "BD {0}/{1}" to "Book {0}/{1}",
        "Téléchargement et ouverture de {0}…" to "Downloading and opening {0}…",
        "Analyse de {0}…" to "Scanning {0}…",
        "Scan terminé · {0} album(s) dans la bibliothèque" to "Scan complete · books in library: {0}",
        "Format non reconnu : {0}" to "Unsupported format: {0}",
        "Réimport {0}/{1}" to "Restoring {0}/{1}",
        "{0} album(s) réimporté(s)" to "Books restored: {0}",
        "{0}/{1} réimporté(s) · sources indisponibles conservées dans les albums supprimés" to "{0}/{1} restored · unavailable sources kept in removed books",
        "Couverture · {0}" to "Cover · {0}",
        "Impossible d’obtenir l’accès à ce dossier : {0}" to "Unable to access this folder: {0}",
        "OneDrive indisponible ({0})." to "OneDrive unavailable ({0}).",
        "Service bibliographique indisponible ({0})" to "Book information service unavailable ({0})",
        "Dernière recherche : {0}" to "Last lookup: {0}",
        " · {0} avis" to " · {0} reviews",
        "{0}\nPage {1} sur {2}" to "{0}\nPage {1} of {2}",
        "{0} albums\n{1} en local · {2} dans le cloud" to "{0} books\n{1} local · {2} in the cloud",
        "BubbleBD est gratuite et permet de lire vos BD sur téléphone, sans compte à créer. Elle ouvre les PDF, CBZ / ZIP et CBR / RAR ; certains formats d’image dépendent du téléphone." to "BubbleBD is a free app for reading your comics on your phone, with no account to create. It opens PDF, CBZ / ZIP and CBR / RAR files; support for some image formats depends on your device.",
        "Touchez deux fois une case pour l’agrandir ou revenir à la page entière. Pincez pour zoomer ou voir les cases voisines, puis déplacez l’image. Le pincement s’arrête au cadrage de la case : relâchez pour reprendre le défilement, ou pincez à nouveau pour continuer à zoomer. Un toucher affiche les commandes. Le sens de lecture se change dans l’en-tête et l’assombrissement dans Réglages." to "Double-tap a panel to enlarge it or return to the full page. Pinch to zoom or reveal neighbouring panels, then drag to move the image. Pinching stops at the panel framing: release to resume navigation, or pinch again to continue zooming. Tap once to show controls. Change reading direction in the header and dimming in Settings.",
        "Les cases sont calculées sur votre téléphone, avec préparation de la page suivante. La détection peut se tromper : les cases reconnues restent utilisables. Sans case reconnue, la page entière reste affichée et le mode automatique reprend sur les pages suivantes. Une bulle ambiguë reste visible dans les cases concernées ; deux cases consécutives d’une même ligne peuvent être affichées ensemble." to "Panels are detected on your phone, with the next page prepared in advance. Detection can make mistakes: recognised panels remain usable. If no panels are recognised, the full page stays visible and automatic reading resumes on later pages. An ambiguous speech balloon remains visible in the relevant panels; two consecutive panels on the same row may be shown together.",
        "Ajoutez un dossier depuis Android, y compris Google Drive si disponible, ou connectez votre OneDrive personnel. Les sous-dossiers sont aussi parcourus. La bibliothèque regroupe les séries et reprend votre progression. « Télécharger » conserve une copie pour lire sans connexion. Vider le cache garde ces copies." to "Add a folder through Android, including Google Drive if available, or connect your personal OneDrive. Subfolders are scanned too. The library groups series and remembers your progress. Download keeps an offline copy. Clearing the cache does not remove these copies.",
        "« Supprimer » retire l’album de BubbleBD et ses copies de lecture, sans toucher à l’original. Ses infos, sa progression et sa première page restent enregistrées, même si l’original devient inaccessible. Dans « Albums supprimés », vous pouvez réimporter un album, une sélection ou tous les albums ; la réimportation nécessite l’accès au fichier." to "Remove takes a book and its reading copies out of BubbleBD without changing the original. Its details, progress and first page are kept, even if the original becomes unavailable. In Removed books, you can restore one book, a selection or all books; restoring requires access to the file.",
        "La recherche se lance dans Réglages ou à l’import, pour les nouveaux albums. Elle privilégie les ouvertures récentes, puis les nouveaux imports. Le bouton manuel permet aussi de réexaminer les fiches complètes. Ouvrir l’application ne relance pas la recherche. Après un échec, vous pouvez la relancer depuis Réglages." to "Information lookup starts from Settings or when new books are imported. Recently opened books are prioritised, followed by new imports. The manual button can also recheck complete records. Opening the app does not restart lookup. After a failure, you can try again from Settings.",
        "Les renseignements déjà connus servent à identifier l’album. La base commune est consultée avant Mistral ; des catalogues et sites publics complètent la recherche. Les résultats de Mistral sont partagés pour éviter de refaire le travail. Les quotas gratuits peuvent retarder la recherche. Les informations incertaines restent vides ; une autre édition du même album peut servir de référence. Une fiche identifiée peut corriger les champs déjà renseignés, y compris le titre. Les champs absents de la source restent conservés. Le résumé se lit en entier en défilant." to "Known details help identify the book. The shared database is checked before Mistral; public catalogues and websites provide additional information. Mistral results are shared to avoid repeating lookups. Free quotas may delay searches. Uncertain fields remain blank; another edition of the same book may be used as a reference. A verified match can update existing fields, including the title. Fields missing from the source are kept. Scroll to read the full summary.",
        "Votre bibliothèque et votre progression restent sur ce téléphone. La recherche en ligne transmet les renseignements utiles à l’identification ; en dernier recours, du texte et une miniature de couverture peuvent être analysés. Aucun album complet n’est envoyé. La miniature n’est pas conservée dans la base commune." to "Your library and reading progress stay on this phone. Online lookup sends information useful for identifying the book; as a last resort, cover text and a thumbnail may be analysed. Complete books are never sent. The thumbnail is not stored in the shared database.",
        "Logiciel libre sous licence GNU AGPL v3 ou ultérieure. Les BD et leurs images restent la propriété de leurs ayants droit. Modèle de détection : Leandro Narosky, basé sur Ultralytics YOLO26n / Manga109-s. LiteRT, Tesseract4Android et tessdata_fast : Apache-2.0 ; libarchive : BSD. BnF : Licence Ouverte ; Wikipédia : CC BY-SA, avec attribution des extraits." to "Free software under GNU AGPL v3 or later. Comics and their images remain the property of their rights holders. Detection model: Leandro Narosky, based on Ultralytics YOLO26n / Manga109-s. LiteRT, Tesseract4Android and tessdata_fast: Apache-2.0; libarchive: BSD. BnF: Open Licence; Wikipedia: CC BY-SA, with attribution for excerpts."
    )
}
