CREATE TABLE IF NOT EXISTS cache(key TEXT PRIMARY KEY,expires INTEGER NOT NULL,body TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS cache_expiry ON cache(expires);
CREATE TABLE IF NOT EXISTS quota(day INTEGER PRIMARY KEY,calls INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS pace(key TEXT PRIMARY KEY,expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS lookup_locks(key TEXT PRIMARY KEY,token TEXT NOT NULL,expires INTEGER NOT NULL);
